% parameters of the brushless isotropic drive

%p: number of pole pairs
p=2

%fi_pm: flux linkage generated by permanent magnets [Wb]
fi_pm=0.1;

%Ld: d axis inductance [H]
Ld=100e-3;

%Lq: q axis inductance [H]
Lq=100e-3;

%r: stator phase resistance [Ohm]
r=10;

%j:total inertia of the rotating masses [kgm^2]
j=0.001;

%ki: integral coefficient of the PI regulator
ki=600

%kp: proportional coefficient of the PI regulator
kp=ki*0.005

%fsw: switching frequency [Hz]
fsw=2000;

